apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: apache2-deployment 
  labels:
    app: httpd 
  spec:
    replicas: 2 
    selector:
      matchLabels: 
        app: httpd
    template: 
      metadata:
        labels: 
          app: httpd
      spec: 
        containers:
        - name: httpd
          image: httpd:2.4.41 
          ports:
          - containerPort: 80
